package org.fstore.Entity;
// Generated Sep 3, 2019, 5:38:32 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BusinessStore generated by hbm2java
 */
public class BusinessStore implements java.io.Serializable {

	private Byte storeId;
	private CustomerAddress customerAddress;
	private byte[] name;
	private byte managerStaffId;
	private Date lastUpdate;
	private Set bussinessStaffs = new HashSet(0);
	private Set inventories = new HashSet(0);
	private Set customers = new HashSet(0);

	public BusinessStore() {
	}

	public BusinessStore(CustomerAddress customerAddress, byte managerStaffId, Date lastUpdate) {
		this.customerAddress = customerAddress;
		this.managerStaffId = managerStaffId;
		this.lastUpdate = lastUpdate;
	}

	public BusinessStore(CustomerAddress customerAddress, byte[] name, byte managerStaffId, Date lastUpdate,
			Set bussinessStaffs, Set inventories, Set customers) {
		this.customerAddress = customerAddress;
		this.name = name;
		this.managerStaffId = managerStaffId;
		this.lastUpdate = lastUpdate;
		this.bussinessStaffs = bussinessStaffs;
		this.inventories = inventories;
		this.customers = customers;
	}

	public Byte getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Byte storeId) {
		this.storeId = storeId;
	}

	public CustomerAddress getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(CustomerAddress customerAddress) {
		this.customerAddress = customerAddress;
	}

	public byte[] getName() {
		return this.name;
	}

	public void setName(byte[] name) {
		this.name = name;
	}

	public byte getManagerStaffId() {
		return this.managerStaffId;
	}

	public void setManagerStaffId(byte managerStaffId) {
		this.managerStaffId = managerStaffId;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getBussinessStaffs() {
		return this.bussinessStaffs;
	}

	public void setBussinessStaffs(Set bussinessStaffs) {
		this.bussinessStaffs = bussinessStaffs;
	}

	public Set getInventories() {
		return this.inventories;
	}

	public void setInventories(Set inventories) {
		this.inventories = inventories;
	}

	public Set getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set customers) {
		this.customers = customers;
	}

}
