package org.fstore.Entity;
// Generated Aug 10, 2019, 10:55:06 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BusinessStore generated by hbm2java
 */
public class BusinessStore implements java.io.Serializable {

	private Byte storeId;
	private BussinessStaff bussinessStaff;
	private CustomerAddress customerAddress;
	private Date lastUpdate;
	private Set bussinessStaffs = new HashSet(0);
	private Set inventories = new HashSet(0);
	private Set customers = new HashSet(0);

	public BusinessStore() {
	}

	public BusinessStore(BussinessStaff bussinessStaff, CustomerAddress customerAddress, Date lastUpdate) {
		this.bussinessStaff = bussinessStaff;
		this.customerAddress = customerAddress;
		this.lastUpdate = lastUpdate;
	}

	public BusinessStore(BussinessStaff bussinessStaff, CustomerAddress customerAddress, Date lastUpdate,
			Set bussinessStaffs, Set inventories, Set customers) {
		this.bussinessStaff = bussinessStaff;
		this.customerAddress = customerAddress;
		this.lastUpdate = lastUpdate;
		this.bussinessStaffs = bussinessStaffs;
		this.inventories = inventories;
		this.customers = customers;
	}

	public Byte getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Byte storeId) {
		this.storeId = storeId;
	}

	public BussinessStaff getBussinessStaff() {
		return this.bussinessStaff;
	}

	public void setBussinessStaff(BussinessStaff bussinessStaff) {
		this.bussinessStaff = bussinessStaff;
	}

	public CustomerAddress getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(CustomerAddress customerAddress) {
		this.customerAddress = customerAddress;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getBussinessStaffs() {
		return this.bussinessStaffs;
	}

	public void setBussinessStaffs(Set bussinessStaffs) {
		this.bussinessStaffs = bussinessStaffs;
	}

	public Set getInventories() {
		return this.inventories;
	}

	public void setInventories(Set inventories) {
		this.inventories = inventories;
	}

	public Set getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set customers) {
		this.customers = customers;
	}

}
