package org.fstore.Entity;
// Generated Aug 10, 2019, 10:55:06 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BussinessRental generated by hbm2java
 */
public class BussinessRental implements java.io.Serializable {

	private Integer rentalId;
	private BussinessStaff bussinessStaff;
	private Customer customer;
	private Inventory inventory;
	private Date rentalDate;
	private Date returnDate;
	private Date lastUpdate;
	private Set bussinessPayments = new HashSet(0);

	public BussinessRental() {
	}

	public BussinessRental(BussinessStaff bussinessStaff, Customer customer, Inventory inventory, Date rentalDate,
			Date lastUpdate) {
		this.bussinessStaff = bussinessStaff;
		this.customer = customer;
		this.inventory = inventory;
		this.rentalDate = rentalDate;
		this.lastUpdate = lastUpdate;
	}

	public BussinessRental(BussinessStaff bussinessStaff, Customer customer, Inventory inventory, Date rentalDate,
			Date returnDate, Date lastUpdate, Set bussinessPayments) {
		this.bussinessStaff = bussinessStaff;
		this.customer = customer;
		this.inventory = inventory;
		this.rentalDate = rentalDate;
		this.returnDate = returnDate;
		this.lastUpdate = lastUpdate;
		this.bussinessPayments = bussinessPayments;
	}

	public Integer getRentalId() {
		return this.rentalId;
	}

	public void setRentalId(Integer rentalId) {
		this.rentalId = rentalId;
	}

	public BussinessStaff getBussinessStaff() {
		return this.bussinessStaff;
	}

	public void setBussinessStaff(BussinessStaff bussinessStaff) {
		this.bussinessStaff = bussinessStaff;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Inventory getInventory() {
		return this.inventory;
	}

	public void setInventory(Inventory inventory) {
		this.inventory = inventory;
	}

	public Date getRentalDate() {
		return this.rentalDate;
	}

	public void setRentalDate(Date rentalDate) {
		this.rentalDate = rentalDate;
	}

	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getBussinessPayments() {
		return this.bussinessPayments;
	}

	public void setBussinessPayments(Set bussinessPayments) {
		this.bussinessPayments = bussinessPayments;
	}

}
