package org.fstore.Entity;
// Generated Aug 10, 2019, 10:55:06 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Short customerId;
	private BusinessStore businessStore;
	private CustomerAddress customerAddress;
	private String firstName;
	private String lastName;
	private String email;
	private boolean active;
	private Date createDate;
	private Date lastUpdate;
	private Set bussinessPayments = new HashSet(0);
	private Set bussinessRentals = new HashSet(0);

	public Customer() {
	}

	public Customer(BusinessStore businessStore, CustomerAddress customerAddress, String firstName, String lastName,
			boolean active, Date createDate) {
		this.businessStore = businessStore;
		this.customerAddress = customerAddress;
		this.firstName = firstName;
		this.lastName = lastName;
		this.active = active;
		this.createDate = createDate;
	}

	public Customer(BusinessStore businessStore, CustomerAddress customerAddress, String firstName, String lastName,
			String email, boolean active, Date createDate, Date lastUpdate, Set bussinessPayments,
			Set bussinessRentals) {
		this.businessStore = businessStore;
		this.customerAddress = customerAddress;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.active = active;
		this.createDate = createDate;
		this.lastUpdate = lastUpdate;
		this.bussinessPayments = bussinessPayments;
		this.bussinessRentals = bussinessRentals;
	}

	public Short getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Short customerId) {
		this.customerId = customerId;
	}

	public BusinessStore getBusinessStore() {
		return this.businessStore;
	}

	public void setBusinessStore(BusinessStore businessStore) {
		this.businessStore = businessStore;
	}

	public CustomerAddress getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(CustomerAddress customerAddress) {
		this.customerAddress = customerAddress;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getBussinessPayments() {
		return this.bussinessPayments;
	}

	public void setBussinessPayments(Set bussinessPayments) {
		this.bussinessPayments = bussinessPayments;
	}

	public Set getBussinessRentals() {
		return this.bussinessRentals;
	}

	public void setBussinessRentals(Set bussinessRentals) {
		this.bussinessRentals = bussinessRentals;
	}

}
