package org.fstore.Entity;
// Generated Sep 3, 2019, 5:38:32 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerCity generated by hbm2java
 */
public class CustomerCity implements java.io.Serializable {

	private Short cityId;
	private CustomerCountry customerCountry;
	private String city;
	private String cityPostalcode;
	private Date lastUpdate;
	private Set customerAddresses = new HashSet(0);

	public CustomerCity() {
	}

	public CustomerCity(CustomerCountry customerCountry, String city, Date lastUpdate) {
		this.customerCountry = customerCountry;
		this.city = city;
		this.lastUpdate = lastUpdate;
	}

	public CustomerCity(CustomerCountry customerCountry, String city, String cityPostalcode, Date lastUpdate,
			Set customerAddresses) {
		this.customerCountry = customerCountry;
		this.city = city;
		this.cityPostalcode = cityPostalcode;
		this.lastUpdate = lastUpdate;
		this.customerAddresses = customerAddresses;
	}

	public Short getCityId() {
		return this.cityId;
	}

	public void setCityId(Short cityId) {
		this.cityId = cityId;
	}

	public CustomerCountry getCustomerCountry() {
		return this.customerCountry;
	}

	public void setCustomerCountry(CustomerCountry customerCountry) {
		this.customerCountry = customerCountry;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCityPostalcode() {
		return this.cityPostalcode;
	}

	public void setCityPostalcode(String cityPostalcode) {
		this.cityPostalcode = cityPostalcode;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getCustomerAddresses() {
		return this.customerAddresses;
	}

	public void setCustomerAddresses(Set customerAddresses) {
		this.customerAddresses = customerAddresses;
	}

}
