package org.fstore.Entity;
// Generated Aug 10, 2019, 10:55:06 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerAddress generated by hbm2java
 */
public class CustomerAddress implements java.io.Serializable {

	private Short addressId;
	private CustomerCity customerCity;
	private String address;
	private String address2;
	private String district;
	private String postalCode;
	private String phone;
	private Date lastUpdate;
	private Set bussinessStaffs = new HashSet(0);
	private Set customers = new HashSet(0);
	private Set businessStores = new HashSet(0);

	public CustomerAddress() {
	}

	public CustomerAddress(CustomerCity customerCity, String address, String district, String phone, Date lastUpdate) {
		this.customerCity = customerCity;
		this.address = address;
		this.district = district;
		this.phone = phone;
		this.lastUpdate = lastUpdate;
	}

	public CustomerAddress(CustomerCity customerCity, String address, String address2, String district,
			String postalCode, String phone, Date lastUpdate, Set bussinessStaffs, Set customers, Set businessStores) {
		this.customerCity = customerCity;
		this.address = address;
		this.address2 = address2;
		this.district = district;
		this.postalCode = postalCode;
		this.phone = phone;
		this.lastUpdate = lastUpdate;
		this.bussinessStaffs = bussinessStaffs;
		this.customers = customers;
		this.businessStores = businessStores;
	}

	public Short getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Short addressId) {
		this.addressId = addressId;
	}

	public CustomerCity getCustomerCity() {
		return this.customerCity;
	}

	public void setCustomerCity(CustomerCity customerCity) {
		this.customerCity = customerCity;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getBussinessStaffs() {
		return this.bussinessStaffs;
	}

	public void setBussinessStaffs(Set bussinessStaffs) {
		this.bussinessStaffs = bussinessStaffs;
	}

	public Set getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set customers) {
		this.customers = customers;
	}

	public Set getBusinessStores() {
		return this.businessStores;
	}

	public void setBusinessStores(Set businessStores) {
		this.businessStores = businessStores;
	}

}
