package org.fstore.Entity;
// Generated Sep 3, 2019, 5:38:32 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerCountry generated by hbm2java
 */
public class CustomerCountry implements java.io.Serializable {

	private Short countryId;
	private String country;
	private String countryCode;
	private Date lastUpdate;
	private Set customerCities = new HashSet(0);

	public CustomerCountry() {
	}

	public CustomerCountry(String country, Date lastUpdate) {
		this.country = country;
		this.lastUpdate = lastUpdate;
	}

	public CustomerCountry(String country, String countryCode, Date lastUpdate, Set customerCities) {
		this.country = country;
		this.countryCode = countryCode;
		this.lastUpdate = lastUpdate;
		this.customerCities = customerCities;
	}

	public Short getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Short countryId) {
		this.countryId = countryId;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getCustomerCities() {
		return this.customerCities;
	}

	public void setCustomerCities(Set customerCities) {
		this.customerCities = customerCities;
	}

}
