package org.fstore.Entity;
// Generated Aug 10, 2019, 10:55:06 PM by Hibernate Tools 5.2.12.Final

/**
 * InventoryFilmCategoryId generated by hbm2java
 */
public class InventoryFilmCategoryId implements java.io.Serializable {

	private short filmId;
	private byte categoryId;

	public InventoryFilmCategoryId() {
	}

	public InventoryFilmCategoryId(short filmId, byte categoryId) {
		this.filmId = filmId;
		this.categoryId = categoryId;
	}

	public short getFilmId() {
		return this.filmId;
	}

	public void setFilmId(short filmId) {
		this.filmId = filmId;
	}

	public byte getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(byte categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventoryFilmCategoryId))
			return false;
		InventoryFilmCategoryId castOther = (InventoryFilmCategoryId) other;

		return (this.getFilmId() == castOther.getFilmId()) && (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFilmId();
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
