package org.fstore.Entity;
// Generated Aug 10, 2019, 10:55:06 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InventoryActor generated by hbm2java
 */
public class InventoryActor implements java.io.Serializable {

	private Short actorId;
	private String firstName;
	private String lastName;
	private Date lastUpdate;
	private Set inventoryFilmActors = new HashSet(0);

	public InventoryActor() {
	}

	public InventoryActor(String firstName, String lastName, Date lastUpdate) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.lastUpdate = lastUpdate;
	}

	public InventoryActor(String firstName, String lastName, Date lastUpdate, Set inventoryFilmActors) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.lastUpdate = lastUpdate;
		this.inventoryFilmActors = inventoryFilmActors;
	}

	public Short getActorId() {
		return this.actorId;
	}

	public void setActorId(Short actorId) {
		this.actorId = actorId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getInventoryFilmActors() {
		return this.inventoryFilmActors;
	}

	public void setInventoryFilmActors(Set inventoryFilmActors) {
		this.inventoryFilmActors = inventoryFilmActors;
	}

}
