package org.fstore.Entity;
// Generated Aug 10, 2019, 10:55:06 PM by Hibernate Tools 5.2.12.Final

/**
 * InventoryFilmActorId generated by hbm2java
 */
public class InventoryFilmActorId implements java.io.Serializable {

	private short actorId;
	private short filmId;

	public InventoryFilmActorId() {
	}

	public InventoryFilmActorId(short actorId, short filmId) {
		this.actorId = actorId;
		this.filmId = filmId;
	}

	public short getActorId() {
		return this.actorId;
	}

	public void setActorId(short actorId) {
		this.actorId = actorId;
	}

	public short getFilmId() {
		return this.filmId;
	}

	public void setFilmId(short filmId) {
		this.filmId = filmId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventoryFilmActorId))
			return false;
		InventoryFilmActorId castOther = (InventoryFilmActorId) other;

		return (this.getActorId() == castOther.getActorId()) && (this.getFilmId() == castOther.getFilmId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getActorId();
		result = 37 * result + this.getFilmId();
		return result;
	}

}
