package org.fstore.Entity;
// Generated Sep 3, 2019, 5:38:32 PM by Hibernate Tools 5.2.12.Final

/**
 * InventoryFilmText generated by hbm2java
 */
public class InventoryFilmText implements java.io.Serializable {

	private short filmId;
	private String title;
	private String description;

	public InventoryFilmText() {
	}

	public InventoryFilmText(short filmId, String title) {
		this.filmId = filmId;
		this.title = title;
	}

	public InventoryFilmText(short filmId, String title, String description) {
		this.filmId = filmId;
		this.title = title;
		this.description = description;
	}

	public short getFilmId() {
		return this.filmId;
	}

	public void setFilmId(short filmId) {
		this.filmId = filmId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
