package org.fstore.Entity;
// Generated Sep 3, 2019, 5:38:32 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InventoryCategory generated by hbm2java
 */
public class InventoryCategory implements java.io.Serializable {

	private Byte categoryId;
	private String name;
	private Date lastUpdate;
	private Set inventoryFilmCategories = new HashSet(0);

	public InventoryCategory() {
	}

	public InventoryCategory(String name, Date lastUpdate) {
		this.name = name;
		this.lastUpdate = lastUpdate;
	}

	public InventoryCategory(String name, Date lastUpdate, Set inventoryFilmCategories) {
		this.name = name;
		this.lastUpdate = lastUpdate;
		this.inventoryFilmCategories = inventoryFilmCategories;
	}

	public Byte getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Byte categoryId) {
		this.categoryId = categoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getInventoryFilmCategories() {
		return this.inventoryFilmCategories;
	}

	public void setInventoryFilmCategories(Set inventoryFilmCategories) {
		this.inventoryFilmCategories = inventoryFilmCategories;
	}

}
