package org.fstore.Entity;
// Generated Aug 10, 2019, 10:55:06 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * InventoryFilmActor generated by hbm2java
 */
public class InventoryFilmActor implements java.io.Serializable {

	private InventoryFilmActorId id;
	private InventoryActor inventoryActor;
	private InventoryFilm inventoryFilm;
	private Date lastUpdate;

	public InventoryFilmActor() {
	}

	public InventoryFilmActor(InventoryFilmActorId id, InventoryActor inventoryActor, InventoryFilm inventoryFilm,
			Date lastUpdate) {
		this.id = id;
		this.inventoryActor = inventoryActor;
		this.inventoryFilm = inventoryFilm;
		this.lastUpdate = lastUpdate;
	}

	public InventoryFilmActorId getId() {
		return this.id;
	}

	public void setId(InventoryFilmActorId id) {
		this.id = id;
	}

	public InventoryActor getInventoryActor() {
		return this.inventoryActor;
	}

	public void setInventoryActor(InventoryActor inventoryActor) {
		this.inventoryActor = inventoryActor;
	}

	public InventoryFilm getInventoryFilm() {
		return this.inventoryFilm;
	}

	public void setInventoryFilm(InventoryFilm inventoryFilm) {
		this.inventoryFilm = inventoryFilm;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
