package org.fstore.Entity;
// Generated Aug 10, 2019, 10:55:06 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * InventoryFilmCategory generated by hbm2java
 */
public class InventoryFilmCategory implements java.io.Serializable {

	private InventoryFilmCategoryId id;
	private InventoryCategory inventoryCategory;
	private InventoryFilm inventoryFilm;
	private Date lastUpdate;

	public InventoryFilmCategory() {
	}

	public InventoryFilmCategory(InventoryFilmCategoryId id, InventoryCategory inventoryCategory,
			InventoryFilm inventoryFilm, Date lastUpdate) {
		this.id = id;
		this.inventoryCategory = inventoryCategory;
		this.inventoryFilm = inventoryFilm;
		this.lastUpdate = lastUpdate;
	}

	public InventoryFilmCategoryId getId() {
		return this.id;
	}

	public void setId(InventoryFilmCategoryId id) {
		this.id = id;
	}

	public InventoryCategory getInventoryCategory() {
		return this.inventoryCategory;
	}

	public void setInventoryCategory(InventoryCategory inventoryCategory) {
		this.inventoryCategory = inventoryCategory;
	}

	public InventoryFilm getInventoryFilm() {
		return this.inventoryFilm;
	}

	public void setInventoryFilm(InventoryFilm inventoryFilm) {
		this.inventoryFilm = inventoryFilm;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
