package org.fstore.Entity;
// Generated Aug 10, 2019, 10:55:06 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InventoryLanguage generated by hbm2java
 */
public class InventoryLanguage implements java.io.Serializable {

	private Byte languageId;
	private String name;
	private Date lastUpdate;
	private Set inventoryFilmsForLanguageId = new HashSet(0);
	private Set inventoryFilmsForOriginalLanguageId = new HashSet(0);

	public InventoryLanguage() {
	}

	public InventoryLanguage(String name, Date lastUpdate) {
		this.name = name;
		this.lastUpdate = lastUpdate;
	}

	public InventoryLanguage(String name, Date lastUpdate, Set inventoryFilmsForLanguageId,
			Set inventoryFilmsForOriginalLanguageId) {
		this.name = name;
		this.lastUpdate = lastUpdate;
		this.inventoryFilmsForLanguageId = inventoryFilmsForLanguageId;
		this.inventoryFilmsForOriginalLanguageId = inventoryFilmsForOriginalLanguageId;
	}

	public Byte getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Byte languageId) {
		this.languageId = languageId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getInventoryFilmsForLanguageId() {
		return this.inventoryFilmsForLanguageId;
	}

	public void setInventoryFilmsForLanguageId(Set inventoryFilmsForLanguageId) {
		this.inventoryFilmsForLanguageId = inventoryFilmsForLanguageId;
	}

	public Set getInventoryFilmsForOriginalLanguageId() {
		return this.inventoryFilmsForOriginalLanguageId;
	}

	public void setInventoryFilmsForOriginalLanguageId(Set inventoryFilmsForOriginalLanguageId) {
		this.inventoryFilmsForOriginalLanguageId = inventoryFilmsForOriginalLanguageId;
	}

}
