package org.fstore.Entity;
// Generated Sep 3, 2019, 5:38:32 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventory generated by hbm2java
 */
public class Inventory implements java.io.Serializable {

	private Integer inventoryId;
	private BusinessStore businessStore;
	private InventoryFilm inventoryFilm;
	private Date lastUpdate;
	private Set bussinessRentals = new HashSet(0);

	public Inventory() {
	}

	public Inventory(BusinessStore businessStore, InventoryFilm inventoryFilm, Date lastUpdate) {
		this.businessStore = businessStore;
		this.inventoryFilm = inventoryFilm;
		this.lastUpdate = lastUpdate;
	}

	public Inventory(BusinessStore businessStore, InventoryFilm inventoryFilm, Date lastUpdate, Set bussinessRentals) {
		this.businessStore = businessStore;
		this.inventoryFilm = inventoryFilm;
		this.lastUpdate = lastUpdate;
		this.bussinessRentals = bussinessRentals;
	}

	public Integer getInventoryId() {
		return this.inventoryId;
	}

	public void setInventoryId(Integer inventoryId) {
		this.inventoryId = inventoryId;
	}

	public BusinessStore getBusinessStore() {
		return this.businessStore;
	}

	public void setBusinessStore(BusinessStore businessStore) {
		this.businessStore = businessStore;
	}

	public InventoryFilm getInventoryFilm() {
		return this.inventoryFilm;
	}

	public void setInventoryFilm(InventoryFilm inventoryFilm) {
		this.inventoryFilm = inventoryFilm;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getBussinessRentals() {
		return this.bussinessRentals;
	}

	public void setBussinessRentals(Set bussinessRentals) {
		this.bussinessRentals = bussinessRentals;
	}

}
