package org.fstore.Entity;
// Generated Sep 3, 2019, 5:38:32 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InventoryFilm generated by hbm2java
 */
public class InventoryFilm implements java.io.Serializable {

	private Short filmId;
	private InventoryLanguage inventoryLanguageByLanguageId;
	private InventoryLanguage inventoryLanguageByOriginalLanguageId;
	private String title;
	private String description;
	private Date releaseYear;
	private byte rentalDuration;
	private BigDecimal rentalRate;
	private Short length;
	private BigDecimal replacementCost;
	private String rating;
	private String specialFeatures;
	private Date lastUpdate;
	private Set inventories = new HashSet(0);
	private Set inventoryFilmActors = new HashSet(0);
	private Set inventoryFilmCategories = new HashSet(0);

	public InventoryFilm() {
	}

	public InventoryFilm(InventoryLanguage inventoryLanguageByLanguageId, String title, byte rentalDuration,
			BigDecimal rentalRate, BigDecimal replacementCost, Date lastUpdate) {
		this.inventoryLanguageByLanguageId = inventoryLanguageByLanguageId;
		this.title = title;
		this.rentalDuration = rentalDuration;
		this.rentalRate = rentalRate;
		this.replacementCost = replacementCost;
		this.lastUpdate = lastUpdate;
	}

	public InventoryFilm(InventoryLanguage inventoryLanguageByLanguageId,
			InventoryLanguage inventoryLanguageByOriginalLanguageId, String title, String description, Date releaseYear,
			byte rentalDuration, BigDecimal rentalRate, Short length, BigDecimal replacementCost, String rating,
			String specialFeatures, Date lastUpdate, Set inventories, Set inventoryFilmActors,
			Set inventoryFilmCategories) {
		this.inventoryLanguageByLanguageId = inventoryLanguageByLanguageId;
		this.inventoryLanguageByOriginalLanguageId = inventoryLanguageByOriginalLanguageId;
		this.title = title;
		this.description = description;
		this.releaseYear = releaseYear;
		this.rentalDuration = rentalDuration;
		this.rentalRate = rentalRate;
		this.length = length;
		this.replacementCost = replacementCost;
		this.rating = rating;
		this.specialFeatures = specialFeatures;
		this.lastUpdate = lastUpdate;
		this.inventories = inventories;
		this.inventoryFilmActors = inventoryFilmActors;
		this.inventoryFilmCategories = inventoryFilmCategories;
	}

	public Short getFilmId() {
		return this.filmId;
	}

	public void setFilmId(Short filmId) {
		this.filmId = filmId;
	}

	public InventoryLanguage getInventoryLanguageByLanguageId() {
		return this.inventoryLanguageByLanguageId;
	}

	public void setInventoryLanguageByLanguageId(InventoryLanguage inventoryLanguageByLanguageId) {
		this.inventoryLanguageByLanguageId = inventoryLanguageByLanguageId;
	}

	public InventoryLanguage getInventoryLanguageByOriginalLanguageId() {
		return this.inventoryLanguageByOriginalLanguageId;
	}

	public void setInventoryLanguageByOriginalLanguageId(InventoryLanguage inventoryLanguageByOriginalLanguageId) {
		this.inventoryLanguageByOriginalLanguageId = inventoryLanguageByOriginalLanguageId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getReleaseYear() {
		return this.releaseYear;
	}

	public void setReleaseYear(Date releaseYear) {
		this.releaseYear = releaseYear;
	}

	public byte getRentalDuration() {
		return this.rentalDuration;
	}

	public void setRentalDuration(byte rentalDuration) {
		this.rentalDuration = rentalDuration;
	}

	public BigDecimal getRentalRate() {
		return this.rentalRate;
	}

	public void setRentalRate(BigDecimal rentalRate) {
		this.rentalRate = rentalRate;
	}

	public Short getLength() {
		return this.length;
	}

	public void setLength(Short length) {
		this.length = length;
	}

	public BigDecimal getReplacementCost() {
		return this.replacementCost;
	}

	public void setReplacementCost(BigDecimal replacementCost) {
		this.replacementCost = replacementCost;
	}

	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public String getSpecialFeatures() {
		return this.specialFeatures;
	}

	public void setSpecialFeatures(String specialFeatures) {
		this.specialFeatures = specialFeatures;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Set getInventories() {
		return this.inventories;
	}

	public void setInventories(Set inventories) {
		this.inventories = inventories;
	}

	public Set getInventoryFilmActors() {
		return this.inventoryFilmActors;
	}

	public void setInventoryFilmActors(Set inventoryFilmActors) {
		this.inventoryFilmActors = inventoryFilmActors;
	}

	public Set getInventoryFilmCategories() {
		return this.inventoryFilmCategories;
	}

	public void setInventoryFilmCategories(Set inventoryFilmCategories) {
		this.inventoryFilmCategories = inventoryFilmCategories;
	}

}
